name: data_generation_env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - cython
  - imageio=2.4.1
  - numpy=1.15.4
  - numpy-base=1.15.4
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - pandas=0.23.4
  - pillow=5.3.0
  - pyembree=0.1.4
  - pytest=4.0.2
  - pyyaml=3.13
  - scikit-image=0.14.1
  - scipy=1.1.0
  - tqdm=4.28.1
  - trimesh=2.37.7


